language: rust
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.rustup
before_cache:
  - rm -rf /home/travis/.cargo/registry
env:
  global:
    - PROJECT_NAME: ut-cli
    - RUST_BACKTRACE: full
addons:
  apt:
    packages:
      # For building MUSL static builds on Linux.
      - musl-tools
matrix:
  fast_finish: true
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
branches:
  only:
    - master
    # NOTE: Need below regex to trigger deploy on push-tags
    - /^\d+\.\d+\.\d+.*$/
    - /^feature\/.*$/
script: ci/script.bash
before_deploy: ci/before_deploy.bash
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: deployment/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    repo: yoshihitoh/${PROJECT_NAME}
    branch: master
    tags: true
  api_key:
    secure: hBWgsCQcnxM0l4YCqQuqCzUXk0YBwmKZkez3umD3U6mU5bDOZOBHV1JM7k2blFfdW2jutnKXEbd70Pb4rglNksSbUyMlBnn5XRm+iAOWseYkihmpzbAzR7lJ5Dul8b+S1DY66w+lohOX/rdFCbNfXrv++SZK5rg3iAqH5MNzHPsCMb/k5L/qutg1PUD7mGPEx8/D7NBhJh7xnRP5wZ8F2KmiZIGpYKFDpcjLjF7sv+9ybPiN7AfWLCO4yTHG14vLlEvB9LURxHvR20hgvD2BkX4ciOoCuxAt3Bdot9Lj/0vHR8z91WnqBR8IEr0PfA8xtzYlMb8uuCpUVq9IYq1ZlIN1oXX0oScH0iryj3F9C6YgsmBl7C4K4dBALMJqbfT5ekvj1vxmzWkWamhUGRE2MDC5G4Zp4tLM+7W9xz2sPDM/DmvYaDEJItQFTwEci78f2MrW5+R1nijopbGOHI6niuLehtYHWAzXerdJG+z8LgDzz/rebB+0fzEijGquNpC2qMZAO61yNBEefoaY0gkv2AV7/Iq8euN7ZFxLFbV376oPZiKH5mXYa1flSVXHl6AWVfCxp1OdyFOprytgQVjX35X39YYQVJlAfcMPfZ3wjtHTPA1hhxHvhrhXFP1ySsDC/RyTFV891lSwu+lJdzSr5nTNmHCiPliVToEzbyiVqV0=
notifications:
  email:
