language: rust
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.rustup
before_cache:
  - rm -rf /home/travis/.cargo/registry
env:
  global:
    - PROJECT_NAME: ut-cli
    - RUST_BACKTRACE: full
addons:
  apt:
    packages:
      # For building MUSL static builds on Linux.
      - musl-tools
matrix:
  fast_finish: true
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
branches:
  only:
    - master
    # NOTE: Need below regex to trigger deploy on push-tags
    - /^\d+\.\d+\.\d+.*$/
    - /^feature\/.*$/
script: ci/travis/script.bash
